# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-22 00:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='conctent',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 11, 22, 3, 23, 31, 2579), verbose_name='Опубликована'),
        ),
    ]
